version: '2.4'
services:
  react-app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ../src:/usr/src # ローカルをコンテナ内にマウント
    command: sh -c "cd react-sample && yarn start"
    ports:
      - "3000:3000"
    stdin_open: true 